In [1]:
#data preprocessing

In [2]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing datasets
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)
dataset.isnull().sum()

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [3]:
#Fixing missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean')
imputer = imputer.fit(x[:,1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

print(imputer)
print(x)


Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [66]:
dataset.fillna(dataset.mean())

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [42]:
df = pd.read_csv('raw-material-properties.csv')
df

Sample  size1  size2  size3  density1  density2  density3
0   X12558  0.696   2.69   6.38      41.8     17.18      3.90
1   X14728  0.636   2.30   5.14      38.1     12.73      3.89
2   X15468  0.841   2.85   5.20      37.6     13.58      3.98
3   X21364  0.609   2.13   4.62      34.2     11.12      4.02
4   X23671  0.684   2.16   4.87      36.4     12.24      3.92
5   X24055  0.762   2.81   6.36      38.1     13.28      3.89
6   X24905  0.552   2.34   5.03      41.3     16.71      3.86
7   X25917  0.501   2.17   5.09       NaN       NaN       NaN
8   X27871  0.619   2.11   5.13       NaN       NaN       NaN
9   X28690  0.610   2.10   4.18      35.0     12.15      3.86
10  X31385  0.532   2.09   4.93       NaN       NaN       NaN
11  X31813  0.738   2.29   5.47       NaN       NaN       NaN
12  X32807  0.779   2.62   5.59       NaN       NaN       NaN
13  X33943  0.537   2.23   5.41      35.2     11.34      3.99
14  X35035  0.702   2.05   5.10      34.2     10.54      4.02
15  X39223  0.768   2.51   5.09      34.9     12.55      3.90
16  X40503  0.714   2.56   6.03      35.6     12.20      4.02
17  X41400  0.621   2.42   5.10      38.7     14.27      3.98
18  X42988  0.726   2.11   4.69      37.1     13.14      3.98
19  X44749  0.698   2.36   5.40      36.6     12.16      4.01
20  X45295    NaN    NaN    NaN      38.1     13.34      3.89
21  X46965  0.759   2.47   4.83      38.7     14.83      3.89
22  X49666  0.535   2.13   5.23       NaN       NaN       NaN
23  X50678  0.716   2.29   5.45      37.3     13.70      3.92
24  X52894  0.635   2.08   4.94       NaN       NaN       NaN
25  X53925  0.598   2.12   4.69      37.9     13.45      3.78
26  X54254  0.700   2.47   5.22      38.8     14.72      3.92
27  X54272  0.957   2.96   7.37      36.2     13.38      4.20
28  X54394  0.759   2.66   5.36      35.2     12.19      3.98
29  X55408  0.661   2.10   4.27       NaN       NaN       NaN
30  X56952  0.646   2.38   4.51      40.1     15.68      3.86
31  X57095  0.662   2.34   4.71      35.0     12.37      3.90
32  X57128  0.749   2.43   5.16      37.3     13.04      3.92
33  X61870  0.598   2.21   4.90       NaN       NaN       NaN
34  X61888  0.619   2.59   5.81       NaN       NaN       NaN
35  X72736  0.693   2.05   5.02      39.6     15.55      3.94

In [57]:
df.fillna(df.mean())

Sample     size1  size2  size3   density1   density2  density3
0   X12558  0.696000  2.690  6.380  41.800000  17.180000  3.900000
1   X14728  0.636000  2.300  5.140  38.100000  12.730000  3.890000
2   X15468  0.841000  2.850  5.200  37.600000  13.580000  3.980000
3   X21364  0.609000  2.130  4.620  34.200000  11.120000  4.020000
4   X23671  0.684000  2.160  4.870  36.400000  12.240000  3.920000
5   X24055  0.762000  2.810  6.360  38.100000  13.280000  3.890000
6   X24905  0.552000  2.340  5.030  41.300000  16.710000  3.860000
7   X25917  0.501000  2.170  5.090  37.269231  13.363077  3.939231
8   X27871  0.619000  2.110  5.130  37.269231  13.363077  3.939231
9   X28690  0.610000  2.100  4.180  35.000000  12.150000  3.860000
10  X31385  0.532000  2.090  4.930  37.269231  13.363077  3.939231
11  X31813  0.738000  2.290  5.470  37.269231  13.363077  3.939231
12  X32807  0.779000  2.620  5.590  37.269231  13.363077  3.939231
13  X33943  0.537000  2.230  5.410  35.200000  11.340000  3.990000
14  X35035  0.702000  2.050  5.100  34.200000  10.540000  4.020000
15  X39223  0.768000  2.510  5.090  34.900000  12.550000  3.900000
16  X40503  0.714000  2.560  6.030  35.600000  12.200000  4.020000
17  X41400  0.621000  2.420  5.100  38.700000  14.270000  3.980000
18  X42988  0.726000  2.110  4.690  37.100000  13.140000  3.980000
19  X44749  0.698000  2.360  5.400  36.600000  12.160000  4.010000
20  X45295  0.674629  2.348  5.208  38.100000  13.340000  3.890000
21  X46965  0.759000  2.470  4.830  38.700000  14.830000  3.890000
22  X49666  0.535000  2.130  5.230  37.269231  13.363077  3.939231
23  X50678  0.716000  2.290  5.450  37.300000  13.700000  3.920000
24  X52894  0.635000  2.080  4.940  37.269231  13.363077  3.939231
25  X53925  0.598000  2.120  4.690  37.900000  13.450000  3.780000
26  X54254  0.700000  2.470  5.220  38.800000  14.720000  3.920000
27  X54272  0.957000  2.960  7.370  36.200000  13.380000  4.200000
28  X54394  0.759000  2.660  5.360  35.200000  12.190000  3.980000
29  X55408  0.661000  2.100  4.270  37.269231  13.363077  3.939231
30  X56952  0.646000  2.380  4.510  40.100000  15.680000  3.860000
31  X57095  0.662000  2.340  4.710  35.000000  12.370000  3.900000
32  X57128  0.749000  2.430  5.160  37.300000  13.040000  3.920000
33  X61870  0.598000  2.210  4.900  37.269231  13.363077  3.939231
34  X61888  0.619000  2.590  5.810  37.269231  13.363077  3.939231
35  X72736  0.693000  2.050  5.020  39.600000  15.550000  3.940000

In [62]:
df1=df.iloc[:,1:].values
df1

array([[ 0.696,  2.69 ,  6.38 , 41.8  , 17.18 ,  3.9  ],
       [ 0.636,  2.3  ,  5.14 , 38.1  , 12.73 ,  3.89 ],
       [ 0.841,  2.85 ,  5.2  , 37.6  , 13.58 ,  3.98 ],
       [ 0.609,  2.13 ,  4.62 , 34.2  , 11.12 ,  4.02 ],
       [ 0.684,  2.16 ,  4.87 , 36.4  , 12.24 ,  3.92 ],
       [ 0.762,  2.81 ,  6.36 , 38.1  , 13.28 ,  3.89 ],
       [ 0.552,  2.34 ,  5.03 , 41.3  , 16.71 ,  3.86 ],
       [ 0.501,  2.17 ,  5.09 ,    nan,    nan,    nan],
       [ 0.619,  2.11 ,  5.13 ,    nan,    nan,    nan],
       [ 0.61 ,  2.1  ,  4.18 , 35.   , 12.15 ,  3.86 ],
       [ 0.532,  2.09 ,  4.93 ,    nan,    nan,    nan],
       [ 0.738,  2.29 ,  5.47 ,    nan,    nan,    nan],
       [ 0.779,  2.62 ,  5.59 ,    nan,    nan,    nan],
       [ 0.537,  2.23 ,  5.41 , 35.2  , 11.34 ,  3.99 ],
       [ 0.702,  2.05 ,  5.1  , 34.2  , 10.54 ,  4.02 ],
       [ 0.768,  2.51 ,  5.09 , 34.9  , 12.55 ,  3.9  ],
       [ 0.714,  2.56 ,  6.03 , 35.6  , 12.2  ,  4.02 ],
       [ 0.621,  2.42 ,  5.1  ,

In [63]:
#Fixing missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean')
imputer = imputer.fit(df1[:, :])
df1[:, :] = imputer.transform(df1[:, :])

print(imputer)
print(df1)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)
[[ 0.696       2.69        6.38       41.8        17.18        3.9       ]
 [ 0.636       2.3         5.14       38.1        12.73        3.89      ]
 [ 0.841       2.85        5.2        37.6        13.58        3.98      ]
 [ 0.609       2.13        4.62       34.2        11.12        4.02      ]
 [ 0.684       2.16        4.87       36.4        12.24        3.92      ]
 [ 0.762       2.81        6.36       38.1        13.28        3.89      ]
 [ 0.552       2.34        5.03       41.3        16.71        3.86      ]
 [ 0.501       2.17        5.09       37.26923077 13.36307692  3.93923077]
 [ 0.619       2.11        5.13       37.26923077 13.36307692  3.93923077]
 [ 0.61        2.1         4.18       35.         12.15        3.86      ]
 [ 0.532       2.09        4.93       37.26923077 13.36307692  3.93923077]
 [ 0.738       2.29        5.47       37.26923077 13.36307692  3.93923077]
 [ 0.779       2.62    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [4]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X = LabelEncoder()
x[:,0] = labelencoder_X.fit_transform(x[:,0])
onehotencoder = OneHotEncoder(categorical_features = [0])
x = onehotencoder.fit_transform(x).toarray()

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

print(x)
print(y)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]
[0 1 0 0 1 1 0 1 0 1]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [77]:
dp=pd.read_csv('banklist.csv')
dp

Bank Name                City  \
0                                  Fayette County Bank          Saint Elmo   
1    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
2                                       First NBC Bank         New Orleans   
3                                        Proficio Bank  Cottonwood Heights   
4                        Seaway Bank and Trust Company             Chicago   
5                               Harvest Community Bank          Pennsville   
6                                          Allied Bank            Mulberry   
7                         The Woodbury Banking Company            Woodbury   
8                               First CornerStone Bank     King of Prussia   
9                                   Trust Company Bank             Memphis   
10                          North Milwaukee State Bank           Milwaukee   
11                              Hometown National Bank            Longview   
12                                 The Bank of Georgia      Peachtree City   
13                                        Premier Bank              Denver   
14                                      Edgebrook Bank             Chicago   
15                                          Doral Bank            San Juan   
16                   Capitol City Bank & Trust Company             Atlanta   
17                             Highland Community Bank             Chicago   
18                   First National Bank of Crestview            Crestview   
19                                  Northern Star Bank             Mankato   
20              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
21               The National Republic Bank of Chicago             Chicago   
22                                      NBRS Financial          Rising Sun   
23                               GreenChoice Bank, fsb             Chicago   
24                            Eastside Commercial Bank             Conyers   
25                             The Freedom State Bank              Freedom   
26                                         Valley Bank     Fort Lauderdale   
27                                         Valley Bank              Moline   
28                         Slavie Federal Savings Bank             Bel Air   
29                               Columbia Savings Bank          Cincinnati   
..                                                 ...                 ...   
521                                       IndyMac Bank            Pasadena   
522                           First Integrity Bank, NA             Staples   
523                                  ANB Financial, NA         Bentonville   
524                                          Hume Bank                Hume   
525                             Douglass National Bank         Kansas City   
526                                  Miami Valley Bank            Lakeview   
527                                            NetBank          Alpharetta   
528                          Metropolitan Savings Bank          Pittsburgh   
529                                    Bank of Ephraim             Ephraim   
530                                      Reliance Bank        White Plains   
531              Guaranty National Bank of Tallahassee         Tallahassee   
532                                Dollar Savings Bank              Newark   
533                               Pulaski Savings Bank        Philadelphia   
534              First National Bank of Blanchardville      Blanchardville   
535                              Southern Pacific Bank            Torrance   
536                        Farmers Bank of Cheneyville         Cheneyville   
537                                      Bank of Alamo               Alamo   
538                         AmTrade International Bank             Atlanta   
539                       Connecticut Bank of Commerce            Stamford   
540                                   New Century Bank     Shelby T

In [81]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_dp = LabelEncoder()
dp[:,2] = labelencoder_dp.fit_transform(dp[:,2])
onehotencoder = OneHotEncoder(categorical_features = [2])
dp = onehotencoder.fit_transform(dp).toarray()

#labelencoder_y = LabelEncoder()
#y = labelencoder_y.fit_transform(y)

print(dp)
#print(y)

TypeError: '(slice(None, None, None), 2)' is an invalid key

In [12]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)
print(x_train)
print(x_test)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
