In [2]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print(A)

print()

Af = np.array([1,2,3],float)
print(Af)

[[1 2 3]
 [4 5 6]]

[ 1.  2.  3.]


In [11]:
print(np.arange(0,2,0.3))

print(np.linspace(0,2*np.pi,6))

A = np.zeros((2,3))
print(A)

print(A.shape)

# default is float

[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]
[ 0.          1.25663706  2.51327412  3.76991118  5.02654825  6.28318531]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
(2, 3)


In [16]:
print(np.arange(0,10,2))

print(np.linspace(0,10,10))

[0 2 4 6 8]
[  0.           1.11111111   2.22222222   3.33333333   4.44444444
   5.55555556   6.66666667   7.77777778   8.88888889  10.        ]


In [23]:
A = np.ones((2,3))
print(A)

A.shape

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


(2, 3)

In [28]:
np.random.random((2,3))


array([[ 0.80480417,  0.57224462,  0.98177246],
       [ 0.05663251,  0.4865359 ,  0.63969258]])

In [37]:
A = np.zeros((2,2))
C=A
C[1,0]=1
print(A)

# original matrix will also be changed

[[ 0.  0.]
 [ 1.  0.]]


In [40]:
A = np.ones((3,3))

A[2,1]=0

print(A)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  0.  1.]]


In [46]:
a = np.arange(10).reshape((2,5))
print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.T)
print(a.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
(2, 5)
10
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
int32


In [49]:
a = np.arange(4)
print(a)

b = np.array([2,3,2,4])
print(b)

print(a*b)
print(b-a)

c = [2,3,4,5]
print(a*c)

[0 1 2 3]
[2 3 2 4]
[ 0  3  4 12]
[2 2 0 1]
[ 0  3  8 15]


In [50]:
A = np.ones((3,3))

print(3*A-1)

# array broadcating is one to all

[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


In [67]:
A = np.random.random((3,3))
print(A)

print(3*A-1)

[[ 0.22154006  0.49589869  0.65050269]
 [ 0.72763543  0.0289097   0.37170938]
 [ 0.4000183   0.11293812  0.57366507]]
[[-0.33537983  0.48769608  0.95150807]
 [ 1.18290629 -0.91327091  0.11512813]
 [ 0.2000549  -0.66118564  0.72099521]]


In [55]:
# float - 128 bits
# int - 64 bits
# default float 32


In [62]:
u = [2,2,2]
v = [1,2,3]

print(np.inner(u,v))

print(np.outer(u,v))

print(np.dot(u,v))

12
[[2 4 6]
 [2 4 6]
 [2 4 6]]
12


In [4]:
import numpy as np
u = np.array([2,2,2,1,2,3,7,8,9])
#print(u.reshape((3,3)))

v = np.array([1,2,3,4,5,6,4,3,2])
#print(v.reshape((3,3)))

print(np.inner(u.reshape((3,3)),v.reshape((3,3))))

print(np.outer(u.reshape((3,3)),v.reshape((3,3))))

print(np.dot(u.reshape((3,3)),v.reshape((3,3))))

[[ 12  30  18]
 [ 14  32  16]
 [ 50 122  70]]
[[ 2  4  6  8 10 12  8  6  4]
 [ 2  4  6  8 10 12  8  6  4]
 [ 2  4  6  8 10 12  8  6  4]
 [ 1  2  3  4  5  6  4  3  2]
 [ 2  4  6  8 10 12  8  6  4]
 [ 3  6  9 12 15 18 12  9  6]
 [ 7 14 21 28 35 42 28 21 14]
 [ 8 16 24 32 40 48 32 24 16]
 [ 9 18 27 36 45 54 36 27 18]]
[[18 20 22]
 [21 21 21]
 [75 81 87]]
