In [2]:
import numpy as np
x = np.float32(1.0)  # default is float32
x

1.0

In [3]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [10]:
z = np.arange(3, dtype=np.uint8)
print(z)

[0 1 2]


In [18]:
z = np.arange(3, dtype=np.uint8)
print(z.dtype)
#dtype('uint8')

uint8


In [17]:
x=np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [19]:
x=np.array([[1.+0.j,2.+0.j], [0.+0.j,0.+0.j],[1.+1.j,3.+0.j]])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [20]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,10,dtype=np.float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [23]:
#call by reference (maximum times)


In [24]:
c=np.arange(8).reshape(2,2,2)
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [27]:
b=np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
x=np.arange(10)
print(x)
print(x[2])
print(x[-2])

x.shape=(2,5)
print(x[1,3])
print(x[1,-1])

[0 1 2 3 4 5 6 7 8 9]
2
8
8
9


In [42]:
x=np.arange(10)
print(x)
print(x[2:5])
print(x[:-7])
print(x[1:7:2])

y=np.arange(35).reshape(5,7)
print(y)
print(y[1:5:2,::3])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 1 2]
[1 3 5]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7 10 13]
 [21 24 27]]


In [2]:
import numpy as np
a=np.array([10,20,15,60])
print(a)
p=a.reshape((2,2))
print(p)

print(a)
print(p.sum())
print(a.min())
print(p.max(axis=0))
print(p.min(axis=1))

[10 20 15 60]
[[10 20]
 [15 60]]
[10 20 15 60]
105
10
[15 60]
[10 15]


In [56]:
a=np.floor(10*np.random.random((3,4)))
print(a)
print(a.shape)
print(a.ravel())

a.shape=(6,2)
print(a)
print(a.transpose())

[[2. 4. 5. 6.]
 [0. 7. 8. 5.]
 [8. 0. 7. 4.]]
(3, 4)
[2. 4. 5. 6. 0. 7. 8. 5. 8. 0. 7. 4.]
[[2. 4. 5. 6.]
 [0. 7. 8. 5.]
 [8. 0. 7. 4.]]
[[2. 4.]
 [5. 6.]
 [0. 7.]
 [8. 5.]
 [8. 0.]
 [7. 4.]]
[[2. 5. 0. 8. 8. 7.]
 [4. 6. 7. 5. 0. 4.]]
