In [1]:
#linear algebra

In [2]:
from numpy import *
from numpy.linalg import *
a = array([[1.0,2.0],[3.0,4.0]])
print(a)
print(a.transpose())
print(inv(a))

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
u=eye(2) #identity matrix (unit 2x2 matrix) "eye" represents "I"
print(u)

[[1. 0.]
 [0. 1.]]


In [4]:
j=array([[0.0,-1.0],[1.0,0.0]])
print(dot(j,j)) # matrix product

[[-1.  0.]
 [ 0. -1.]]


In [5]:
u=eye(2)
trace(u)

2.0

In [8]:
y=array([[5.],[7.]])
a = array([[1.0,2.0],[3.0,4.0]])
solve(a,y) # solve linear matrix equation

array([[-3.],
       [ 4.]])

In [7]:
j=array([[0.0,-1.0],[1.0,0.0]])
print(dot(j,j))
eig(j)


[[-1.  0.]
 [ 0. -1.]]


(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [17]:
A=matrix('1.0 2.0; 3.0 4.0')
print(A)
print(type(A))
print(A.T)
X=matrix('5.0 7.0')
Y=X.T

print(A*Y) # product
print(A.I) # inverse of a matrix
print(solve(A,Y))

[[1. 2.]
 [3. 4.]]
<class 'numpy.matrix'>
[[1. 3.]
 [2. 4.]]
[[19.]
 [43.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-3.]
 [ 4.]]
